-- Migration 0001 — schema minimo para que el agente IA lea el catalogo desde Supabase.
-- Pega este archivo completo en el SQL Editor de Supabase (https://supabase.com/dashboard) y ejecuta.
--
-- IMPORTANTE: Si ya tienes tablas tours/categories en tu BD legacy (Render), este
-- script crea/actualiza la version Supabase para alimentar el agente. No borra nada
-- existente — usa CREATE TABLE IF NOT EXISTS y INSERT ... ON CONFLICT DO NOTHING.

create extension if not exists "pgcrypto";

-- ---------------------------------------------------------------------------
-- categories
-- ---------------------------------------------------------------------------
create table if not exists public.categories (
  id           bigint generated by default as identity primary key,
  name         text not null,
  slug         text not null unique,
  color_hex    text,
  created_at   timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- tours
-- ---------------------------------------------------------------------------
create table if not exists public.tours (
  id                  bigint generated by default as identity primary key,
  name                text not null,
  slug                text not null unique,
  description         text,
  short_description   text,
  price_adult         integer not null,
  price_child         integer,
  duration            text not null,
  departure_time      text,
  return_time         text,
  departure_point     text,
  max_people          integer,
  includes            text[] not null default '{}',
  excludes            text[] not null default '{}',
  avg_rating          numeric(3,2) not null default 0,
  total_bookings      integer not null default 0,
  status              text not null default 'active'
                       check (status in ('active', 'paused', 'archived')),
  category_id         bigint references public.categories(id) on delete set null,
  cover_image_url     text,
  gallery_urls        text[] not null default '{}',
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);

create index if not exists tours_status_idx on public.tours (status);
create index if not exists tours_avg_rating_idx on public.tours (avg_rating desc);

-- ---------------------------------------------------------------------------
-- RLS — el agente lee con SUPABASE_SERVICE_ROLE_KEY (bypass RLS automatico).
-- Para el cliente publico expone SELECT solo de tours activos.
-- ---------------------------------------------------------------------------
alter table public.tours enable row level security;
alter table public.categories enable row level security;

drop policy if exists "tours publicos solo activos" on public.tours;
create policy "tours publicos solo activos"
  on public.tours for select
  using (status = 'active');

drop policy if exists "categorias lectura publica" on public.categories;
create policy "categorias lectura publica"
  on public.categories for select
  using (true);

-- ---------------------------------------------------------------------------
-- Seed: las 6 ofertas del FALLBACK_CATALOG del agente, asi el modo demo
-- funciona contra Supabase real y no contra el array hardcoded.
-- ---------------------------------------------------------------------------
insert into public.categories (name, slug, color_hex) values
  ('Playa', 'playa', '#0D5C8A'),
  ('Aventura', 'aventura', '#2D6A4F'),
  ('Cultura', 'cultura', '#C9A05C')
on conflict (slug) do nothing;

insert into public.tours
  (name, slug, price_adult, duration, includes, avg_rating, status, category_id)
values
  ('Cabo San Juan — Parque Tayrona', 'cabo-san-juan', 160000, '8 horas',
    array['Transporte ida y vuelta','Entrada al parque','Almuerzo tipico'], 4.8, 'active',
    (select id from public.categories where slug = 'playa')),
  ('Playa Blanca — Rodadero', 'playa-blanca-rodadero', 95000, '6 horas',
    array['Lancha ida y vuelta','Snorkel guiado','Frutas y agua'], 4.6, 'active',
    (select id from public.categories where slug = 'playa')),
  ('Pueblito Tayrona — Sierra Nevada', 'pueblito-tayrona', 220000, '10 horas',
    array['Guia indigena Kogui','Transporte','Almuerzo tipico'], 4.9, 'active',
    (select id from public.categories where slug = 'aventura')),
  ('Minca — cascadas y cafe', 'minca-cascadas', 130000, '7 horas',
    array['Transporte 4x4','Tour cafetal','Bano en cascada Marinka'], 4.7, 'active',
    (select id from public.categories where slug = 'aventura')),
  ('City tour Santa Marta', 'city-tour-santa-marta', 60000, '4 horas',
    array['Guia bilingue','Centro historico','Quinta de San Pedro'], 4.4, 'active',
    (select id from public.categories where slug = 'cultura')),
  ('Bahia Concha — playa virgen', 'bahia-concha', 110000, '7 horas',
    array['Transporte','Entrada parque','Hidratacion'], 4.5, 'active',
    (select id from public.categories where slug = 'playa'))
on conflict (slug) do nothing;

-- Verificacion rapida: deberia retornar 6 filas.
-- select id, name, slug, price_adult, avg_rating from public.tours
--   where status = 'active' order by avg_rating desc;
